version = 0.1

[default]
[default.global.parameters]
stack_name = "apigw-s3-lambda-sam-stack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "apigw-s3-lambda-sam-stack"
s3_bucket = ""  # SAM will create this automatically
region = "us-east-1"
image_repositories = []
parameter_overrides = "Stage=\"dev\" BucketName=\"your-unique-bucket-name-$(date +%s)\""
resolve_s3 = true
s3_prefix = "apigw-s3-lambda-sam-stack"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Production environment configuration
[prod]
[prod.deploy.parameters]
stack_name = "apigw-s3-lambda-sam-stack-prod"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
region = "us-east-1"
parameter_overrides = "Stage=\"prod\" BucketName=\"your-prod-bucket-name\""
resolve_s3 = true
s3_prefix = "apigw-s3-lambda-sam-stack-prod"

# Development environment configuration  
[dev]
[dev.deploy.parameters]
stack_name = "apigw-s3-lambda-sam-stack-dev"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
region = "us-east-1"
parameter_overrides = "Stage=\"dev\" BucketName=\"your-dev-bucket-name\""
resolve_s3 = true
s3_prefix = "apigw-s3-lambda-sam-stack-dev"
